server:
  port: 8084
  
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
     
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
      
jwt:
  secret: mySuperSecretKeyForJWT12345678901234567890
  expiration: 86400000
  
